# Generated by Django 3.0.4 on 2020-07-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_auto_20200714_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='size',
            field=models.IntegerField(choices=[(0, 'S'), (1, 'M'), (2, 'L')], default=0),
        ),
    ]
